
before_install:
 - sudo add-apt-repository -y ppa:codegear/release
 - sudo apt-get -qq update
 - sudo apt-get install premake4
 
script:
 - premake4 embed
 - premake4 gmake
 - make -j8
 - bin/release/premake5 test

